# base image
FROM continuumio/anaconda3:latest
# includes flask, pillow, pandas, numpy, matplotlib

WORKDIR /app

COPY . .

EXPOSE 8888

RUN pip --no-cache-dir install \
	flasgger==0.9.5 \
	torch==1.9.0 \
	torchvision==0.10.0

CMD python api-pytorch.py